######################################################
# Create a new draft release when a new tag is pushed.
######################################################
name: Draft a new release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  create-draft-release:
    name: Create draft release
    runs-on: ubuntu-latest
    steps:
      ######################################################################
      # get the tag name
      ######################################################################
      - name: Get tag from the push
        id: set_variables
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      ######################################################################
      # create a new draft release
      ######################################################################
      - name: Create new draft release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.set_variables.outputs.tag }}
          release_name: v${{ steps.set_variables.outputs.tag }}
          body: ${{ github.event.head_commit.message }}
          draft: true
          prerelease: false